name: Publish to NuGet

on:
  workflow_dispatch:

jobs:
  publish:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Extract version from .csproj
      run: |
        VERSION=$(grep -oP '(?<=<Version>).*?(?=</Version>)' UFEDLib/UFEDLib.csproj)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Extracted version: $VERSION"

    #- name: Display version in logs
    #  run: echo "Building NuGet package with version: $VERSION"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Create output directory
      run: mkdir -p nupkgs

    - name: Check current directory
      run: pwd && ls -la

    - name: Pack the NuGet package
      run: dotnet pack --configuration Release --no-build --version $VERSION --output nupkgs 

    - name: List the contents of the output directory
      run: ls -R nupkgs

    - name: Publish to NuGet
      run: dotnet nuget push "nupkgs/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
    
