name: Publish to NuGet

on:
  workflow_dispatch:

jobs:
  publish:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Extract version from .csproj
      run: |
        echo "VERSION=$(grep -oP '(?<=<Version>).*?(?=</Version>)' UFEDLib/UFEDLib.csproj)" >> $GITHUB_ENV
        echo "Extracted version: $VERSION"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore


    - name: Pack the NuGet package
      run: dotnet pack --configuration Release --no-build --output nupkgs --version $VERSION

    - name: Publish to NuGet
      run: dotnet nuget push "nupkgs/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
    
